---

- hosts: all
  become: yes
  vars:
    file_version: 1.0
  tasks:
    - name: install stuff
      apt: 
        name:{{item}}
        update_cache:yes
        state:latest
        enabled:true
      with_items:
        - vim
        - nano
        - apache2
      when: ansible_os_family == "Debian"

    - name: install stuff
      yum: 
        name:{{item}}
        update_cache:yes
        state:latest
      with_items:
        - vim
        - nano
        - httpd
      # notify: start httpd
      when: ansible_os_family == "RedHat"

    - name: install index.html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: 0777
    - name: start httpd
      service: name=httpd enabled=yes state=restarted
      when: ansible_os_family == "RedHat"