---

- hosts: centos
  become: yes
  vars:
    - var_thing: "never gonna"
  
  tasks:
    - name: echo stuff
      command: echo -e "{{var_thing}} give you up,\n{{var_thing}} let you down,\n{{var_thing}} run around and desert you"
      register: results

    - name: show results
      # debug: msg="the variable var_thing is set to - {{var_thing}}"
      # debug: msg={{results['stdout_lines']}}
      debug: msg={{results.stdout_lines}}